language: generic

sudo: required

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - VERBOSE=1
  matrix:
    - DISTRIBUTIONS=wheezy
    - DISTRIBUTIONS=jessie
    - DISTRIBUTIONS=stretch

script:
  - make build
  - make lint

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
