# List of splits.
splits:
  - prefix: alt-galaxy
    target: git@github.com:manala/debian-package-alt-galaxy.git
  - prefix: ansible
    target: git@github.com:manala/debian-package-ansible.git
  - prefix: backup-manager
    target: git@github.com:manala/debian-package-backup-manager.git
  - prefix: cgroupfs-mount
    target: git@github.com:manala/debian-package-cgroupfs-mount.git
  - prefix: gitsplit
    target: git@github.com:manala/debian-package-gitsplit.git
  - prefix: keepalived
    target: git@github.com:manala/debian-package-keepalived.git
  - prefix: mailhog
    target: git@github.com:manala/debian-package-mailhog.git
  - prefix: mongo-express
    target: git@github.com:manala/debian-package-mongo-express.git
  - prefix: ngrok
    target: git@github.com:manala/debian-package-ngrok.git
  - prefix: oauth2-proxy
    target: git@github.com:manala/debian-package-oauth2-proxy.git
  - prefix: opcache-dashboard
    target: git@github.com:manala/debian-package-opcache-dashboard.git
  - prefix: pam-ssh-agent-auth
    target: git@github.com:manala/debian-package-pam-ssh-agent-auth.git
  - prefix: phantomjs
    target: git@github.com:manala/debian-package-phantomjs.git
  - prefix: phpmyadmin
    target: git@github.com:manala/debian-package-phpmyadmin.git
  - prefix: phppgadmin
    target: git@github.com:manala/debian-package-phppgadmin.git
  - prefix: phpredisadmin
    target: git@github.com:manala/debian-package-phpredisadmin.git
  - prefix: python-jinja2
    target: git@github.com:manala/debian-package-python-jinja2.git
  - prefix: python-pathlib2
    target: git@github.com:manala/debian-package-python-pathlib2.git
  - prefix: rtail
    target: git@github.com:manala/debian-package-rtail.git
  - prefix: splitsh-lite
    target: git@github.com:manala/debian-package-splitsh-lite.git
  - prefix: supervisor
    target: git@github.com:manala/debian-package-supervisor.git
  - prefix: thefuck
    target: git@github.com:manala/debian-package-thefuck.git
  - prefix: vault
    target: git@github.com:manala/debian-package-vault.git

# List of references to split (defined as regexp)
origins:
  - ^master$
