language: generic

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - VERBOSE=1
  matrix:
    - DISTRIBUTIONS=wheezy  PART=1/2
    - DISTRIBUTIONS=wheezy  PART=2/2
    - DISTRIBUTIONS=jessie  PART=1/2
    - DISTRIBUTIONS=jessie  PART=2/2
    - DISTRIBUTIONS=stretch PART=1/2
    - DISTRIBUTIONS=stretch PART=2/2

script:
  - make build.diff
  - make lint.diff

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
