define gitsplit
ifeq ($(shell uname -s),Darwin)
	docker run \
		--rm \
		--tty --interactive \
		--volume $(MANALA_CURRENT_DIR):/srv \
		--volume $(HOME)/.ssh:/root/.ssh \
		jderusse/gitsplit
else
	docker run \
		--rm \
		--tty --interactive \
		--volume $(MANALA_CURRENT_DIR):/srv \
		--volume $(SSH_AUTH_SOCK):/ssh-agent \
		--env SSH_AUTH_SOCK=/ssh-agent \
		jderusse/gitsplit
endif
endef
