#!/bin/sh

service=sensuctl

case "$1" in
    remove)
    rm /lib/systemd/system/${service}.service
    systemctl --system daemon-reload >/dev/null || true

	;;

    upgrade|deconfigure|failed-upgrade)
	;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
